# Generated by Django 4.2.20 on 2025-04-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_id', models.BigIntegerField(unique=True)),
                ('course_name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_text_color', models.CharField(default='#92d4a7', max_length=7)),
                ('assignment_border_color', models.CharField(default='#92d4a7', max_length=7)),
                ('assignment_background_color', models.CharField(default='#1a1a1a', max_length=7)),
                ('progress_bar_color', models.CharField(default='#6b8cff', max_length=7)),
            ],
        ),
    ]
